config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'sessions#new'

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/contact'

  get 'static_pages/unauthorized'

  resources :tournaments

  resources :articles

  resources :city

  resources :users

  resources :courts

  resources :reservations

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  match '/gettoken', to: 'users#gettoken', via: 'post'
  match '/getreservations', to: 'reservations#getreservations', via: 'post'
  match '/getuserreservations', to: 'reservations#getuserreservations', via: 'get'

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  dragonfly_accessor :image
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all
    @host_address = request.protocol + request.host_with_port
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
    @host_address = request.protocol + request.host_with_port
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:title, :content, :from, :to, :contact, :author, :surface, :image, :city, :address)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<%= form_for(@tournament) do |f| %>
    <% if @tournament.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

          <ul>
            <% @tournament.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content %>
    </div>
    <div class="field">
      <%= f.label :from %><br>
      <%= f.date_select :from %>
    </div>
    <div class="field">
      <%= f.label :to %><br>
      <%= f.date_select :to %>
    </div>
    <div class="field">
      <%= f.label :contact %><br>
      <%= f.text_field :contact %>
    </div>
    <div class="field">
      <%= f.label :author %><br>
      <%= f.text_field :author %>
    </div>
    <div class="field">
      <%= f.label :surface %><br>
      <%= f.text_field :surface %>
    </div>
    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </div>
    <div class="field">
      <%= f.label :city %><br>
      <%= f.text_field :city %>
    </div>
    <div class="field">
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tournaments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>From</th>
      <th>To</th>
      <th>Contact</th>
      <th>Author</th>
      <th>Surface</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tournaments.each do |tournament| %>
      <tr>
        <td><%= tournament.title %></td>
        <td><%= tournament.content %></td>
        <td><%= tournament.from %></td>
        <td><%= tournament.to %></td>
        <td><%= tournament.contact %></td>
        <td><%= tournament.author %></td>
        <td><%= tournament.surface %></td>
        <td><%= link_to 'Show', tournament %></td>
        <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
        <td><%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tournament', new_tournament_path %>

app/views/tournaments/new.html.erb
<h1>New Tournament</h1>

<%= render 'form' %>

<%= link_to 'Back', tournaments_path %>

app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tournament.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tournament.content %>
</p>

<p>
  <strong>From:</strong>
  <%= @tournament.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @tournament.to %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @tournament.contact %>
</p>

<p>
  <strong>Author:</strong>
  <%= @tournament.author %>
</p>

<p>
  <strong>Surface:</strong>
  <%= @tournament.surface %>
</p>

<%= link_to 'Edit', edit_tournament_path(@tournament) %> |
<%= link_to 'Back', tournaments_path %>